#!/bin/bash

KEY_SAVE_FOLDER_PATH=$PKI_FOLDER_NAME/$KEY_SAVE_FOLDER
FULL_CLIENT_CERTIFICATE_NAME=$CLIENT_CERT_NAME.$TENANT_NAME
CLIENT_CERTIFICATE=$CERT_ISSUER  #$CLIENT_CERT_NAME.$CERT_ISSUER

aws ec2 export-client-vpn-client-configuration --client-vpn-endpoint-id $CLIENT_VPN_ID --profile $AWSCLIPROFILE --region $REGION --output text > $FULL_CLIENT_CERTIFICATE_NAME.ovpn

sed -i "s/"$CLIENT_VPN_ID"/"$TENANT_NAME.$CLIENT_VPN_ID"/g" $FULL_CLIENT_CERTIFICATE_NAME.ovpn
echo "<cert>" >> $FULL_CLIENT_CERTIFICATE_NAME.ovpn
cat $KEY_SAVE_FOLDER_PATH/$CLIENT_CERTIFICATE.crt >> $FULL_CLIENT_CERTIFICATE_NAME.ovpn
echo "</cert>" >> $FULL_CLIENT_CERTIFICATE_NAME.ovpn

echo "<key>" >> $FULL_CLIENT_CERTIFICATE_NAME.ovpn
cat $KEY_SAVE_FOLDER_PATH/$CLIENT_CERTIFICATE.key >> $FULL_CLIENT_CERTIFICATE_NAME.ovpn
echo "</key>" >> $FULL_CLIENT_CERTIFICATE_NAME.ovpn

#open ~/$FULL_CLIENT_CERTIFICATE_NAME.ovpn
#
#mkdir -p ~/ClientCertificates
#mv ~/$FULL_CLIENT_CERTIFICATE_NAME.ovpn ~/ClientCertificates
